trigger: 
  branches:
    include:
      - main
pool:
  vmImage: ubuntu-latest
stages:
  - stage: Sonarqube
    dependsOn:
    jobs:
      - job:
        steps:
          - checkout: self
            fetchDepth: 0
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: Sonarqube
              organization: milence
              scannerMode: CLI
              configMode: manual
              cliProjectKey: cvce_Terraform
              cliProjectName: Terraform
              cliSources: '.'
          - task: SonarCloudAnalyze@1
            inputs:
              jdkversion: 'JAVA_HOME_11_X64'
          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'
